version: '3.4'

services:
  jenkins.api:
    container_name: jenkins-api
    image: priyanshu5/jenkinsapi
    build:
      context: .
      dockerfile: Jenkins.API/Dockerfile
    ports:
      - 8001:80
